# Exercises

Exercises from chapter 5 from the book ```Quantum Computing for Computer Scientists``` solved with a bit of Python help.

* [Exercise 5.3.1](#exe_5_3_1)
* [Exercise 5.3.2](#exe_5_3_2)
* [Exercise 5.4.1](#exe_5_4_1)
* [Exercise 5.4.2](#exe_5_4_2)

In [1]:
import sys

if "../../" not in sys.path:
    sys.path.append("../../")

In [2]:
import numpy as np
from programs.matrix_utils import is_unitary_matrix
from programs.matrix_utils import is_unitary_matrix_complex
from programs.gates.cnot import CNOTGate
from programs.gates.toffoli import ToffoliGate 

## <a name="exe_5_3_1"></a> Exercise 5.3.1

Show that the _CNOT_ gate is its own inverse by multiplying
the corresponding matrix by itself and arriving at the identity matrix.

### Answer

In [9]:
# CNOT gate
cnot = CNOTGate()
matrix = cnot.matrix
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [4]:
I = np.eye(matrix.shape[0])

In [5]:
print("CNOT has its own inverse={0}".format(np.allclose(I, np.dot(matrix, matrix))))

CNOT has its own inverse=True


## <a name="exe_5_3_2"></a> Exercise 5.3.2

Show that the Toffoli gate is its own inverse.

### Answer

In [6]:
# CNOT gate
toffoli = ToffoliGate()
matrix = toffoli.matrix
print(matrix)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]


In [7]:

I = np.eye(matrix.shape[0])

In [8]:
print("Toffoli gate has its own inverse={0}".format(np.allclose(I, np.dot(matrix, matrix))))

Toffoli gate has its own inverse=True


## <a name="exe_5_4_1"></a> Exercise 5.4.1

Show that the Pauli matrices are unitary matrices.

### Answer

This is similar to exercise 4.4.1. A matrix $\mathbf{U}$ is a unitary matrix iff 

$$\mathbf{U}^T\mathbf{U}=\mathbf{U}\mathbf{U}^T=\mathbf{I}$$

In [3]:
X = np.array([[0.0, 1.0], [1.0, 0.0]])

In [4]:
print("Is X unitary?={0}".format(is_unitary_matrix_complex(matrix=X)))

Is X unitary?=True


In [5]:
Y = np.array([[0.0, -1.0j], [1.0j, 0.0]])

In [7]:
print("Is Y unitary?={0}".format(is_unitary_matrix_complex(matrix=Y)))

Is Y unitary?=True


In [8]:
Z = np.array([[1.0, 0.0], [0.0, -1.0]])

In [9]:
print("Is Z unitary?={0}".format(is_unitary_matrix(matrix=Z)))

Is Z unitary?=True


## <a name="exe_5_4_2"></a> Exercise 5.4.2

**TODO**