# Exercises

Exercises from chapter 4 from the book ```Quantum Computing for Computer Scientists``` solved with a bit of Python help.

## Exercise 4.4.1

Verify that the following matrices are unitary matrices

### Answer

A matrix is a unitary matrix iff 

$$\mathbf{U}^T\mathbf{U}=\mathbf{U}\mathbf{U}^T=\mathbf{I}$$

In [1]:
import numpy as np

In [2]:
u1 = np.array([[0., 1.0],[1.0, 0.0]])

In [4]:
np.dot(u1.T,u1)

array([[1., 0.],
       [0., 1.]])

In [5]:
np.dot(u1, u1.T)

array([[1., 0.],
       [0., 1.]])

So $U_1$ is unitary

In [8]:
u2 = np.array([[np.sqrt(2)/2., np.sqrt(2)/2.],[np.sqrt(2)/2., -np.sqrt(2)/2.]])

In [9]:
np.dot(u2.T,u2)

array([[1.00000000e+00, 4.26642159e-17],
       [4.26642159e-17, 1.00000000e+00]])

In [10]:
np.dot(u2, u2.T)

array([[1.00000000e+00, 4.26642159e-17],
       [4.26642159e-17, 1.00000000e+00]])

The product of two unitary matrices is also unitary

In [13]:
product = np.dot(u1, u2)

In [14]:
np.dot(product, product.T)

array([[1.00000000e+00, 4.26642159e-17],
       [4.26642159e-17, 1.00000000e+00]])

In [15]:
np.dot(product.T, product)

array([[ 1.00000000e+00, -4.26642159e-17],
       [-4.26642159e-17,  1.00000000e+00]])

Hence, the product of two unitary matrices is a unitary matrix itself.

## Exercise 4.4.2

Consider the initial state vector 

$$ |\psi(t_0) \rangle = (1, 0, 0, 0)$$

and the unitary map 

$$U = \begin{bmatrix} 0 && 1.0/\sqrt{2} && 1.0/\sqrt{2} && 0 \\
                      i/\sqrt{2} && 0 && 0 && 1.0/\sqrt{2} \\
                      1.0/\sqrt{2} && 0 && 0 && i/\sqrt{2} \\
                      0 && 1.0/\sqrt{2} && -1.0/\sqrt{2} && 0 \end{bmatrix}$$

What is the system state after three steps?

### Answer

In [39]:
psi = np.array([1.0, 0.0, 0.0, 0.0])

In [40]:
U = np.array([[0., 1.0/np.sqrt(2), 1.0/np.sqrt(2) ,0.],
              [1j/np.sqrt(2), 0., 0., 1.0/np.sqrt(2)],
              [1.0/np.sqrt(2), 0., 0., 1j/np.sqrt(2)],
              [0., 1.0/np.sqrt(2), -1.0/np.sqrt(2), 0.]])

In [42]:
old_state = psi
for itr in range(3):
    psi = U.dot(old_state)
    print("State is: {0}".format(psi))
    old_state = psi

State is: [0.        +0.j         0.        +0.70710678j 0.70710678+0.j
 0.        +0.j        ]
State is: [ 0.5+0.5j  0. +0.j   0. +0.j  -0.5+0.5j]
State is: [ 0.        +0.j         -0.70710678+0.70710678j  0.        +0.j
  0.        +0.j        ]


## Exercise 4.5.1

Consider the state space $\mathbb{C}^{n \times m}$ where $n=m=4$ and the following applitude coefficients

$$c_{0,0} = c_{0,1}=\dots=c_{3,3} = 1 +i$$

What is the probability of finding the first particle at location $x_1$ and the second one at $y_1$?

### Answer

The superimposed state is 

$$|\psi \rangle = c_{0,0}|x_0 \rangle \otimes |y_0 \rangle + c_{0,1}|x_0 \rangle \otimes |y_1 \rangle +\dots + c_{3,3}|x_3 \rangle \otimes |y_3 \rangle $$

The probability of finding the first particle at location $x_1$ and the second one at $y_1$ is given by

$$p(x_1, y_1) = \frac{|c_{1,1}|^2}{\sum_{i} \sum_{j} |c_{i,j}|^2}$$

In [17]:
import numpy as np

In [18]:
psi = np.array([1. + 1j, 1. + 1j, 1.+1j, 1.+1j, 1.+1j,
                1. + 1j, 1. + 1j, 1.+1j, 1.+1j, 1.+1j,
                1. + 1j, 1. + 1j, 1.+1j, 1.+1j, 1.+1j, 1.+1j ])

In [19]:
ss = 0.0

for item in psi:
    ss += np.abs(item)**2
    
print(ss)

32.00000000000001


In [20]:
print("p(x_1, y_1)={0}".format(np.abs(psi[1])**2/ss))

p(x_1, y_1)=0.0625
